env:
  browser: true
  node: true
  commonjs: true
  es2021: true
extends:
  - eslint:recommended
  - standard
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2021
rules: {
  "prettier/prettier": ["error", {}, { "usePrettierrc": true }]
}
