version: "3.9"
services:
  app:
    image: node:16-alpine
    container_name: app
    restart: unless-stopped
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3090:3090"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: examplepwd
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
